name: Deploy to Server via SFTP

on:
  push:
    branches:
      - master # Adjust this as necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Adjust to match your project's Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: access978123064.webspace-data.io
          port: 22 # Default SFTP port, change if yours is different
          local_path: ./dist
          remote_path: /
          sftp_only: true # Use this if your server only allows SFTP connections
          password: ${{ secrets.SFTP_PASSWORD }} # This will use the password for authentication
